"""empty message

Revision ID: 76ddcd611f49
Revises: b2397a61111e
Create Date: 2021-06-01 16:11:20.934367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ddcd611f49'
down_revision = 'b2397a61111e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'nickname')
    op.alter_column('users', 'avatar', new_column_name="picture")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'picture', new_column_name="avatar")
    # ### end Alembic commands ###
