"""empty message

Revision ID: 8bd6940c3fcd
Revises: eef97a1b71bc
Create Date: 2021-06-05 04:34:47.121478

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as sp
import greenbat.database.types


# revision identifiers, used by Alembic.
revision = '8bd6940c3fcd'
down_revision = 'eef97a1b71bc'
branch_labels = None
depends_on = None


def upgrade():
    enum_rating = sp.ENUM('DISLIKED', 'MIXED', 'LIKED', 'LOVED', name='rating')
    enum_rating.create(op.get_bind())
    enum_completition = sp.ENUM('NOT_APPLICABLE', 'UNPLAYED', 'STARTED', 'BEATEN', 'COMPLETED', 'MASTERED', name='completition')
    enum_completition.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('rating', sa.Enum('DISLIKED', 'MIXED', 'LIKED', 'LOVED', name='rating'), nullable=True))
    op.add_column('elements', sa.Column('completition', sa.Enum('NOT_APPLICABLE', 'UNPLAYED', 'STARTED', 'BEATEN', 'COMPLETED', 'MASTERED', name='completition'), nullable=True))
    op.create_unique_constraint(None, 'metadata_steam', ['appid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metadata_steam', type_='unique')
    op.drop_column('elements', 'completition')
    op.drop_column('elements', 'rating')
    # ### end Alembic commands ###

    op.execute("DROP TYPE completition;")
    op.execute("DROP TYPE rating;")
