"""empty message

Revision ID: b2397a61111e
Revises: 
Create Date: 2021-06-01 05:25:27.478562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import greenbat.database.types

# revision identifiers, used by Alembic.
revision = 'b2397a61111e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_table('elements',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.uuid'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('steam',
    sa.Column('steamid', greenbat.database.types.SteamID(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('steamid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steam')
    op.drop_table('elements')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
