"""empty message

Revision ID: d4746548af4e
Revises: 
Create Date: 2021-06-03 04:38:38.803507

"""
from alembic import op
import sqlalchemy as sa
import greenbat.database.types


# revision identifiers, used by Alembic.
revision = 'd4746548af4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_table('accounts_steam',
    sa.Column('steamid', greenbat.database.types.SteamID(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_table('elements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elements')
    op.drop_table('accounts_steam')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
