"""empty message

Revision ID: eef97a1b71bc
Revises: d4746548af4e
Create Date: 2021-06-03 04:48:50.411689

"""
from alembic import op
import sqlalchemy as sa
import greenbat.database.types


# revision identifiers, used by Alembic.
revision = 'eef97a1b71bc'
down_revision = 'd4746548af4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_custom',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('creator_sub', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_sub'], ['users.sub'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('metadata_steam',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_steam')
    op.drop_table('metadata_custom')
    # ### end Alembic commands ###
