[database]
uri = "postgresql://steffo@/greenbat"

[auth]
authorization = "https://ryg.eu.auth0.com/authorize?audience=https://greenbat.ryg.one&prompt=consent"
token = "https://ryg.eu.auth0.com/oauth/token"
refresh = "https://ryg.eu.auth0.com/oauth/token"
jwks = "https://ryg.eu.auth0.com/.well-known/jwks.json"
audience = "https://greenbat.ryg.one"

[api]
alloworigins = ["*"]
port = 30044

[api.list]
maxlimit = 500
